### ISSUE TITLE
Module not found: Error: Can't resolve 'bson-objectid'

### ISSUE THREAD

**Issue by pbpraveen1988** [gregchamberlain/react-dnd-layout#2]
Hello ,

I installed your library but i am getting the Errors which you can see below.

ERROR in ./~/react-dnd-layout/lib/layout_provider.js
Module not found: Error: Can't resolve 'bson-objectid'

Please help me on this.

Thank You

**Comment by gregchamberlain** [comment]
Thanks for opening an issue to bring this to my attention! I've been working on a new and improved version of this library for the past few weeks and just published it to npm. If you upgrade to version 0.3 everything should work. The documentation for the new version is up to date in this repos README
